### ISSUE TITLE
An error occured in the  Instrumentation Phase

### ISSUE THREAD

**Issue by shijiansj** [SocietyMaster/AFLIoT#2]
here is the command and result:

the command is : 
python afl-instrument.py -f D:\IOT_file\datset\20140617\x64\VirusShare_f99c1d6cd8874aabedd0129cf592f5ed -o D:\design_experiment\output  -i D:\design_experiment\IDA_Pro_v7.0_Portable\ida64.exe

and it is the output:
Traceback (most recent call last):
  File "afl-instrument.py", line 701, in <module>
    main()
  File "afl-instrument.py", line 696, in main
    parameters = setup()
  File "afl-instrument.py", line 680, in setup
    bbs = json.loads(open(jsonconfig, 'r').read())
IOError: [Errno 2] No such file or directory: 'D:\\design_experiment\\AFLIoT\\cov-instrument\\VirusShare_f99c1d6cd8874aabedd0129cf592f5ed.config'

how to solve the problem? and where is the config file?

**Comment by andrewson97** [comment]
I am also facing the same issue 

@shijiansj  have you found any solution for this problem? 

@xcdu @SocietyMaster please help with the errors
